# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunica7', '0002_usuarios_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios_productos',
            old_name='usuarios',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='usuarios_productos',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunica7.Productos'),
        ),
    ]
