# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-26 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunica7', '0003_auto_20181221_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
