# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-17 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0048_auto_20181214_0601'),
        ('callcenter', '0049_auto_20181217_1508'),
    ]

    operations = [
    ]
