# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0062_auto_20181218_1917'),
        ('callcenter', '0063_auto_20181218_2010'),
    ]

    operations = [
    ]
