# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0064_merge_20181218_2304'),
        ('callcenter', '0065_auto_20181218_2335'),
    ]

    operations = [
    ]
