# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0074_auto_20181220_1555'),
        ('callcenter', '0069_auto_20181219_2258'),
    ]

    operations = [
    ]
