# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0079_auto_20181220_1651'),
        ('callcenter', '0078_auto_20181220_2034'),
    ]

    operations = [
    ]
