# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-02 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0103_auto_20190102_1244'),
        ('callcenter', '0105_auto_20181231_1153'),
    ]

    operations = [
    ]
