# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-17 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0107_auto_20190111_1724'),
        ('callcenter', '0111_auto_20190109_1634'),
    ]

    operations = [
    ]
