# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-21 18:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colasIN', '0003_auto_20181220_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.IntegerField(blank=True, null=True)),
                ('fono', models.IntegerField(blank=True, null=True)),
                ('destino', models.IntegerField(blank=True, null=True)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('atendidas', models.IntegerField(blank=True, null=True)),
                ('contactadas', models.IntegerField(blank=True, null=True)),
                ('est_ag_predictivo', models.IntegerField(blank=True, null=True)),
                ('canal', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 12, 21, 18, 40, 20, 657542))),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAgente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 18, 40, 20, 667858), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AddField(
            model_name='agente',
            name='estado',
            field=models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_estadorelated', to='colasIN.EstadoAgente'),
        ),
        migrations.AddField(
            model_name='agente',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrelated', to=settings.AUTH_USER_MODEL),
        ),
    ]
