# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-21 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colasIN', '0004_auto_20181221_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2018, 12, 21, 19, 20, 32, 467908))),
            ],
        ),
        migrations.AlterField(
            model_name='agente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 12, 21, 19, 20, 32, 458381)),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 19, 20, 32, 468543), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='venta',
            field=models.ForeignKey(blank=True, help_text='Codigo Venta', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='colasIN.Venta'),
        ),
    ]
