# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-21 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colasIN', '0005_auto_20181221_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=100, null=True, verbose_name='DNI')),
                ('telefono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=100, null=True)),
                ('importe', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_promesa', models.CharField(blank=True, max_length=100, null=True)),
                ('deuda', models.CharField(blank=True, max_length=100, null=True)),
                ('deuda_pendiente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 12, 21, 19, 48, 11, 796195))),
            ],
        ),
        migrations.AlterField(
            model_name='agente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 12, 21, 19, 48, 11, 781406)),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 19, 48, 11, 797653), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 19, 48, 11, 794238)),
        ),
    ]
