# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-28 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colasIN', '0010_auto_20181228_2256'),
        ('colasIN', '0018_auto_20181228_0056'),
    ]

    operations = [
    ]
