# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-31 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colasIN', '0020_auto_20181229_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 12, 31, 11, 34, 10, 511743)),
        ),
        migrations.AlterField(
            model_name='agente',
            name='t_estado',
            field=models.DateTimeField(db_column='t_estado', default=datetime.datetime(2018, 12, 31, 11, 34, 10, 511766)),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 12, 31, 11, 34, 10, 517080)),
        ),
        migrations.AlterField(
            model_name='logestadoagente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2018, 12, 31, 11, 34, 10, 510912)),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 11, 34, 10, 517670), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 11, 34, 10, 516600)),
        ),
        migrations.AddField(
            model_name='produccionaudio',
            name='produccion',
            field=models.ForeignKey(blank=True, help_text='Produccion', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='colasIN.Produccion'),
        ),
    ]
