# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-09 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colasIN', '0031_auto_20190108_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColasinAcd',
            fields=[
                ('id_acd', models.AutoField(primary_key=True, serialize=False)),
                ('did_campana', models.CharField(db_column='DID_Campana', max_length=45)),
                ('numero_llamado', models.CharField(db_column='Numero_Llamado', max_length=45)),
                ('numero_entrante', models.CharField(db_column='Numero_Entrante', max_length=45)),
                ('channel_entrante', models.CharField(db_column='Channel_Entrante', max_length=50)),
                ('tiempo', models.IntegerField(db_column='Tiempo')),
                ('flag', models.IntegerField()),
                ('uniqueid', models.CharField(max_length=30)),
                ('fin', models.IntegerField()),
                ('age_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tie_ing', models.DateTimeField()),
                ('tie_acd', models.DateTimeField()),
                ('tie_tra', models.DateTimeField()),
                ('tie_con', models.DateTimeField()),
                ('tie_fin', models.DateTimeField()),
                ('tie_acw', models.DateTimeField()),
                ('id_ori_campana', models.IntegerField()),
                ('sql', models.IntegerField()),
                ('codhu', models.IntegerField(db_column='CodHU')),
                ('bill', models.IntegerField()),
                ('asterisk', models.IntegerField()),
                ('audio', models.CharField(max_length=100, unique=True)),
                ('valorllamada', models.CharField(max_length=200)),
                ('id_ori_usuario', models.IntegerField()),
                ('llam_estado', models.IntegerField()),
                ('anexo', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('espera', models.IntegerField()),
                ('pais', models.CharField(max_length=10)),
                ('g_id1', models.CharField(max_length=100)),
                ('g_id2', models.CharField(max_length=100)),
                ('g_id3', models.CharField(max_length=100)),
                ('g_id4', models.CharField(max_length=100)),
                ('g_id5', models.CharField(max_length=100)),
                ('g_id6', models.CharField(max_length=100)),
                ('g_id7', models.CharField(max_length=100)),
                ('g_id8', models.CharField(max_length=100)),
                ('g_id9', models.CharField(max_length=100)),
                ('g_id10', models.CharField(max_length=100)),
                ('accountcode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'colasIN_acd',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='agente',
            name='acd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2019, 1, 9, 16, 33, 57, 874837)),
        ),
        migrations.AlterField(
            model_name='agente',
            name='t_estado',
            field=models.DateTimeField(db_column='t_estado', default=datetime.datetime(2019, 1, 9, 16, 33, 57, 874887)),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2019, 1, 9, 16, 33, 57, 890903)),
        ),
        migrations.AlterField(
            model_name='logestadoagente',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2019, 1, 9, 16, 33, 57, 873177)),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 16, 33, 57, 891749), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='produccionaudio',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2019, 1, 9, 16, 33, 57, 897876)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 16, 33, 57, 889944)),
        ),
    ]
