# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-07 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181105_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='agente',
            name='user',
        ),
        migrations.DeleteModel(
            name='Api',
        ),
        migrations.RemoveField(
            model_name='base',
            name='campania',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='campania',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='dblaster',
            name='campania',
        ),
        migrations.RemoveField(
            model_name='dblaster',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='dllamadas',
            name='id_d_blaster',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Agente',
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Campania',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DBlaster',
        ),
        migrations.DeleteModel(
            name='DLlamadas',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Estadocampania',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
