# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-05 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0028_auto_20181204_1907'),
        ('speech', '0028_auto_20181204_1953'),
    ]

    operations = [
    ]
