# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-12 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0046_auto_20181209_2145'),
        ('speech', '0046_auto_20181211_2137'),
    ]

    operations = [
    ]
