# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-13 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0049_auto_20181212_1849'),
        ('speech', '0048_auto_20181213_1711'),
    ]

    operations = [
    ]
