# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0051_auto_20181214_1551'),
        ('speech', '0051_auto_20181214_0601'),
    ]

    operations = [
    ]
