# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0056_auto_20181218_1602'),
        ('speech', '0053_merge_20181217_1753'),
    ]

    operations = [
    ]
