# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0065_auto_20181218_1917'),
        ('speech', '0066_auto_20181218_2010'),
    ]

    operations = [
    ]
