# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0072_auto_20181219_2258'),
        ('speech', '0077_auto_20181220_1555'),
    ]

    operations = [
    ]
