# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-21 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0083_auto_20181220_2334'),
        ('speech', '0086_auto_20181220_2338'),
    ]

    operations = [
    ]
