# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-26 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0092_auto_20181226_1804'),
        ('speech', '0012_auto_20181128_1708'),
    ]

    operations = [
    ]
