# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-28 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0094_auto_20181228_2256'),
        ('speech', '0103_auto_20181228_0056'),
    ]

    operations = [
    ]
