# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-17 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0003_auto_20190117_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('anexo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('t_inicio_gestion', models.CharField(blank=True, max_length=100, null=True)),
                ('t_fin_gestion', models.CharField(blank=True, max_length=100, null=True)),
                ('t_inicio_llamada', models.CharField(blank=True, max_length=100, null=True)),
                ('t_fin_llamada', models.CharField(blank=True, max_length=100, null=True)),
                ('t_inicio_espera', models.CharField(blank=True, max_length=100, null=True)),
                ('t_fin_espera', models.CharField(blank=True, max_length=100, null=True)),
                ('contactadas', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Departamento')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Distrito')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Provincia')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Departamento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Distrito'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='obserbaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Provincia'),
        ),
    ]
