# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-18 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0005_auto_20190117_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agente',
            old_name='grupor',
            new_name='grupo',
        ),
    ]
