# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0006_auto_20190118_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestiones_externas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(upload_to=b'')),
                ('cartera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Cartera')),
                ('provedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Proveedor')),
                ('tipo_gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discador.Gestion')),
            ],
            options={
                'verbose_name_plural': 'Gestiones externas',
            },
        ),
    ]
