# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-28 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discador', '0007_gestiones_externas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestiones_externas',
            old_name='provedor',
            new_name='proveedor',
        ),
    ]
